#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require

#include "util/ray.glsl"
#include "common/shared.hpp"

#ifndef VPT_CLOUD_MODE
#    define VPT_CLOUD_MODE 1u
#endif

layout(location = 0) rayPayloadInEXT MainRay mainRay;
hitAttributeEXT vec2 attribs;

void main() {
    if (VPT_CLOUD_MODE != 1u) {
        ignoreIntersectionEXT;
        return;
    }
}
