// SPDX-License-Identifier: GPL-3.0-only
// Generated by generate-state-mirror.py. Both APIs receive persistent pipeline state.
package com.radiance.hybrid.mixin;
import com.mojang.blaze3d.platform.GlStateManager;
import com.radiance.hybrid.HybridContext;
import com.radiance.hybrid.OffscreenRenderer;
import org.lwjgl.opengl.*;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.*;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
@Mixin(value = GlStateManager.class, priority = 1100, remap = false)
public abstract class PipelineStateMixin {
    @Inject(method = "_disableScissorTest", at = @At("HEAD"))
    private static void hybrid$_disableScissorTest(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glDisable(GL11.GL_SCISSOR_TEST);
    }
    @Inject(method = "_enableScissorTest", at = @At("HEAD"))
    private static void hybrid$_enableScissorTest(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glEnable(GL11.GL_SCISSOR_TEST);
    }
    @Inject(method = "_scissorBox", at = @At("HEAD"))
    private static void hybrid$_scissorBox(int x, int y, int w, int h, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glScissor(x,y,w,h);
    }
    @Inject(method = "_viewport", at = @At("HEAD"))
    private static void hybrid$_viewport(int x, int y, int w, int h, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glViewport(x,y,w,h);
    }
    @Inject(method = "_disableBlend", at = @At("HEAD"))
    private static void hybrid$_disableBlend(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glDisable(GL11.GL_BLEND);
    }
    @Inject(method = "_enableBlend", at = @At("HEAD"))
    private static void hybrid$_enableBlend(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glEnable(GL11.GL_BLEND);
    }
    @Inject(method = "_blendFunc", at = @At("HEAD"))
    private static void hybrid$_blendFunc(int src, int dst, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glBlendFunc(src,dst);
    }
    @Inject(method = "_blendFuncSeparate", at = @At("HEAD"))
    private static void hybrid$_blendFuncSeparate(int src, int dst, int srcA, int dstA, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL14.glBlendFuncSeparate(src,dst,srcA,dstA);
    }
    @Inject(method = "_blendEquation", at = @At("HEAD"))
    private static void hybrid$_blendEquation(int mode, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL14.glBlendEquation(mode);
    }
    @Inject(method = "_colorMask", at = @At("HEAD"))
    private static void hybrid$_colorMask(boolean r, boolean g, boolean b, boolean a, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glColorMask(r,g,b,a);
    }
    @Inject(method = "_enableColorLogicOp", at = @At("HEAD"))
    private static void hybrid$_enableColorLogicOp(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glEnable(GL11.GL_COLOR_LOGIC_OP);
    }
    @Inject(method = "_disableColorLogicOp", at = @At("HEAD"))
    private static void hybrid$_disableColorLogicOp(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glDisable(GL11.GL_COLOR_LOGIC_OP);
    }
    @Inject(method = "_logicOp", at = @At("HEAD"))
    private static void hybrid$_logicOp(int op, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glLogicOp(op);
    }
    @Inject(method = "_disableDepthTest", at = @At("HEAD"))
    private static void hybrid$_disableDepthTest(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glDisable(GL11.GL_DEPTH_TEST);
    }
    @Inject(method = "_enableDepthTest", at = @At("HEAD"))
    private static void hybrid$_enableDepthTest(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glEnable(GL11.GL_DEPTH_TEST);
    }
    @Inject(method = "_depthFunc", at = @At("HEAD"))
    private static void hybrid$_depthFunc(int func, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glDepthFunc(func);
    }
    @Inject(method = "_depthMask", at = @At("HEAD"))
    private static void hybrid$_depthMask(boolean value, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glDepthMask(value);
    }
    @Inject(method = "_stencilFunc", at = @At("HEAD"))
    private static void hybrid$_stencilFunc(int func, int ref, int mask, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glStencilFunc(func,ref,mask);
    }
    @Inject(method = "_stencilMask", at = @At("HEAD"))
    private static void hybrid$_stencilMask(int mask, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glStencilMask(mask);
    }
    @Inject(method = "_stencilOp", at = @At("HEAD"))
    private static void hybrid$_stencilOp(int fail, int depthFail, int pass, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glStencilOp(fail,depthFail,pass);
    }
    @Inject(method = "_enableCull", at = @At("HEAD"))
    private static void hybrid$_enableCull(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glEnable(GL11.GL_CULL_FACE);
    }
    @Inject(method = "_disableCull", at = @At("HEAD"))
    private static void hybrid$_disableCull(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glDisable(GL11.GL_CULL_FACE);
    }
    @Inject(method = "_polygonMode", at = @At("HEAD"))
    private static void hybrid$_polygonMode(int face, int mode, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glPolygonMode(face,mode);
    }
    @Inject(method = "_enablePolygonOffset", at = @At("HEAD"))
    private static void hybrid$_enablePolygonOffset(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glEnable(GL11.GL_POLYGON_OFFSET_FILL);
    }
    @Inject(method = "_disablePolygonOffset", at = @At("HEAD"))
    private static void hybrid$_disablePolygonOffset(CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glDisable(GL11.GL_POLYGON_OFFSET_FILL);
    }
    @Inject(method = "_polygonOffset", at = @At("HEAD"))
    private static void hybrid$_polygonOffset(float factor, float units, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glPolygonOffset(factor,units);
    }
    @Inject(method = "_clearColor", at = @At("HEAD"))
    private static void hybrid$_clearColor(float r, float g, float b, float a, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glClearColor(r,g,b,a);
    }
    @Inject(method = "_clearDepth", at = @At("HEAD"))
    private static void hybrid$_clearDepth(double value, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glClearDepth(value);
    }
    @Inject(method = "_clearStencil", at = @At("HEAD"))
    private static void hybrid$_clearStencil(int value, CallbackInfo ci) {
        if (!HybridContext.ENABLED) return;
        HybridContext.assertCurrent(); GL11.glClearStencil(value);
    }
    @Inject(method = "_clear", at = @At("HEAD"), cancellable = true)
    private static void hybrid$clear(int mask, boolean checkError, CallbackInfo ci) {
        if (!OffscreenRenderer.isPrivateTarget()) return;
        GL11.glClear(mask);
        ci.cancel(); // Offscreen clear must not clear Radiance's visible Vulkan output.
    }
}
